#%RAML 1.0 ResourceType

get:
  description: Get	a	list	of	<<resourcePathName>>.
  responses:             
    200:
      body: 
        application/json:
          example:  |
            <<exampleCollection>>
    304:
      body:
        application/json:
          example:
            {
              "message": "<<resourcePathName|!singularize>> has not been modified"
            }        
    401:
      body:
        application/json:
          example: |
            {
              "message": "The supplied credentials, if any, are not sufficient to access the resource."
            }         
    404:
      body:
        application/json:
          example: |                
            {
              "message": "<<resourcePathName|!singularize>> not found"
            }
    500:
      body:
        application/json:
          example: |
            {
              "message": "Internal server error occured"
            }         
post:
  description: Creating a new <<resourcePathName|!singularize>>
  body: 
    application/json:
      # type: <<resourcePathName|!singularize>>
      example:
        <<exampleItem>>

  responses:                
    201:                       
      body:
        application/json: 
          type: <<resourcePathName|!singularize>>          
          example: |
              <<exampleCreated>>
    400:
      body:
        application/json:
          # type: result TBD include result
            example: |
              <<exampleResult>>
    401:
      body:
        application/json:
          example: |
            {
              "message": "The supplied credentials, if any, are not sufficient to access the resource."
            }         
    404:
      body:
        application/json:
          example: |                
            {
              "message": "<<resourcePathName|!singularize>> not found"
            }
    500:
      body:
        application/json:
          example: |
            {
              "message": "Internal server error occured"
            }          
              
 
  